### ISSUE TITLE
change reference to plugin.source.lua in index.js

### ISSUE THREAD

**Issue by icanismar** [Iron-Stag-Games/Lync#26]
The lua file for the plugin was moved elsewhere although the old directory is still being referenced in the source code.

In line 615:
```js
let pluginSource = fs.readFileSync(path.resolve(__dirname, 'plugin.source.lua'), { encoding: 'utf8' })
```

Changing it to `RobloxPluginSource/Plugin.lua` fixes the issue.

The error in case you still need it:
```
node:fs:601
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'C:\Users\canis\AppData\Local\Roblox\Lync\plugin.source.lua'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at C:\Users\canis\AppData\Local\Roblox\Lync\index.js:615:25
    at Object.<anonymous> (C:\Users\canis\AppData\Local\Roblox\Lync\index.js:955:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\canis\\AppData\\Local\\Roblox\\Lync\\plugin.source.lua'
}
```

**Comment by hoontee** [comment]
Fixed in Alpha 17.1.
