### ISSUE TITLE
Sync error when creating new empty folder

### ISSUE THREAD

**Issue by Weldify** [Iron-Stag-Games/Lync#35]
Whenever I create a new folder, it fails to sync in properly. When that happens, the only way to get everything up again is to restart studio and start serving again
```
A [assets\server\animations\weapons]
Sync error: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at localPathIsInit (C:\Users\ian\AppData\Local\Roblox\Lync\index.js:105:45)
    at FSWatcher.<anonymous> (C:\Users\ian\AppData\Local\Roblox\Lync\index.js:985:22)
    at FSWatcher.emit (node:events:514:28)
    at FSWatcher.emitWithAll (C:\Users\ian\AppData\Local\Roblox\Lync\node_modules\chokidar\index.js:541:32)
    at FSWatcher._emit (C:\Users\ian\AppData\Local\Roblox\Lync\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleDir (C:\Users\ian\AppData\Local\Roblox\Lync\node_modules\chokidar\lib\nodefs-handler.js:551:53)
    at NodeFsHandler._addToNodeFs (C:\Users\ian\AppData\Local\Roblox\Lync\node_modules\chokidar\lib\nodefs-handler.js:617:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by hoontee** [comment]
I will have this fixed when I get back home in a few hours.

In the meantime, you may be able to edit `index.js` to fix the error.

**Comment by hoontee** [comment]
Fixed. Please update to [Alpha 22.1+](https://github.com/Iron-Stag-Games/Lync/releases) or [enable automatic updates](https://github.com/Iron-Stag-Games/Lync#configuration).
